### ISSUE TITLE
Request: split of ecies

### ISSUE THREAD

**Issue by aakilfernandes** [ethereumjs/node-devp2p#15]
Working on a whsiper implementation. Would be useful to have this as an independent module

**Comment by wanderer** [comment]
I don't think that is going to make sense. node-devp2p should be really be called RPLx. RPLx is just a generic transport. You should be able to run different protocols over it. For example here is how the `eth` subprotocol is handled. 

[on line 37](https://github.com/ethereumjs/node-blockchain-server/blob/master/index.js#L36-L37) the peer is producing a raw stream of data. The [Peer Manager](https://github.com/ethereumjs/node-blockchain-server/blob/master/index.js#L46) is then parsing that stream of data into block and txs. 

Now currecntly we don't have a good way todo steam multiplexing. I would like to do something like [libp2p multilplex](https://github.com/libp2p/js-libp2p-multiplex#js-libp2p-multiplex).

**Comment by aakilfernandes** [comment]
So the reason I wanted a separate package is that it looks like whisper uses the same encryption as rlpx. https://github.com/ethereum/go-ethereum/blob/master/whisper/message.go#L133-L136

So in whisper messages are encrypted twice. Once based on the eventual recipient (node id unkown), and again based on the nearest peer.
